baseURL = "http://example.org/"     # Change to your GitHub Pages URL later
title = "My Math Notes"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en-us"
theme = "PaperMod"


# Enable or disable usage of `hugo mod` if needed
# disableKinds = ["taxonomy", "term"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML (needed for custom anchors or <a name="">)
    [markup.goldmark.extensions]
      # Turn on GitHub-style table, attributes, etc. "math" ensures $$ delimiters pass through
      footnote = true
      table = true
      taskList = true
      definitionList = true
      # Some Hugo versions have "math" extension. If yours does not, you can do the pass-through approach for $...$
      math = true

[languages]
[languages.en]
  languageName = "English"
  weight = 1

[languages.fa]
  languageName = "فارسی"
  weight = 2
  # Farsi is RTL, so we can add a param to help in layout
  [languages.fa.params]
    direction = "rtl"

# If you want to place your default language in a subdir (like /en/), set:
[params]
  math = true

